---
# Ansible Galaxy dependencies for envoy project
# Collections
collections:
  - name: ansible.posix
    version: ">=2.1.0"
  - name: community.general
    version: ">=11.1.0"
  - name: community.vagrant
    version: ">=0.0.0"
  - name: community.vmware
    version: ">=5.7.0"
  - name: vmware.vmware
    version: ">=2.2.0"
  - name: evotor.basic
    version: ">=2.3.0"

# Roles
roles:
  - name: os_bird_bgp
    src: "git@gitlab.evotor.ru:iaac/ansible/bird-bgp.git"  # Исправлен URL и используется SSH
    scm: git
    version: main