---
# Envoy installation settings
envoy_version: "latest"  # Can be "latest" or specific version like "1.28.0"
envoy_user: "envoy"
envoy_group: "envoy"
envoy_system_user: true

# Service type selection
envoy_use_hot_restart: true  # Use hot-restarter.py for zero-downtime restarts

# Hot restart settings
envoy_hot_restart_term_wait: 30  # Seconds to wait for graceful shutdown
envoy_hot_restart_log_level: "INFO"  # Log level for hot-restarter

# BIRD BGP settings (for dependency role)
os_bird_bgp_address: "10.0.1.255"
os_bird_bgp_local_as: 65535
os_bird_neighbour_name: "test_router"
os_bird_neighbour_address: "10.22.1.1"
