---
- name: Install prerequisites for Envoy repository
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Envoy GPG apt key
  ansible.builtin.get_url:
    url: https://apt.envoyproxy.io/signing.key
    dest: /etc/apt/keyrings/envoy-keyring.asc
    mode: '0644'
    force: true

- name: Add Envoy repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/envoy-keyring.asc] https://apt.envoyproxy.io {{ ansible_distribution_release }} main"
    state: present
    filename: envoy

- name: Install Envoy
  ansible.builtin.apt:
    name: envoy{% if envoy_version != 'latest' %}={{ envoy_version }}*{% endif %}
    state: present
    update_cache: true

- name: Create hot-restarter script
  ansible.builtin.template:
    src: hot-restarter.py.j2
    dest: /usr/local/bin/hot-restarter.py
    mode: "0755"
  when: envoy_use_hot_restart
  notify: Reload systemd

- name: Create start-envoy script
  ansible.builtin.copy:
    src: start-envoy.sh
    dest: /usr/local/bin/start-envoy.sh
    mode: "0755"
  when: envoy_use_hot_restart
  notify: Reload systemd

- name: Create systemd service unit
  ansible.builtin.template:
    src: envoy-hot-restart.service.j2
    dest: /etc/systemd/system/envoy.service
    mode: "0644"
  notify: Reload systemd
