---
- name: Check if Envoy package is installed
  ansible.builtin.command: dpkg -l envoy
  register: envoy_package_check
  changed_when: false
  failed_when: false

- name: Get current Envoy version if installed
  ansible.builtin.command: envoy --version
  register: envoy_version_check
  changed_when: false
  failed_when: false
  when: envoy_package_check.rc == 0

- name: Display current Envoy version
  ansible.builtin.debug:
    msg: "Current Envoy version: {{ envoy_version_check.stdout }}"
  when: envoy_package_check.rc == 0 and envoy_version_check.rc == 0
